version: '3.4'

services:
  spareparts.vehicle.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SpareParts=Data Source=mssql;Initial Catalog=Vehicles;user=sa;password=SparePartsTest1234!;MultipleActiveResultSets=True
      - ConnectionStrings__Rebus=Data Source=mssql;Initial Catalog=Vehicles;user=sa;password=SparePartsTest1234!;MultipleActiveResultSets=True
    ports:
      - "32001:80"

  spareparts.part.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SpareParts=Data Source=mssql;Initial Catalog=Parts;user=sa;password=SparePartsTest1234!;MultipleActiveResultSets=True
      - ConnectionStrings__Rebus=Data Source=mssql;Initial Catalog=Parts;user=sa;password=SparePartsTest1234!;MultipleActiveResultSets=True
    ports:
      - "32002:80"
  
  mssql:
    environment:
      SA_PASSWORD: "SparePartsTest1234!"
    ports:
      - "31433:1433"